
import { Service, PortfolioItem, Testimonial, PricingPlan, TeamMember } from './types';

// --- Contact Data ---

export const CONTACT_INFO = {
  name: 'Sandip Kumar Saini',
  phones: ['+91 97796 99699', '+91 88988 28886'],
  email: 'motiondecorator@gmail.com',
  address: 'Mohali, Punjab, India', // Generic location based on phone code, can be updated
  socials: {
    facebook: 'https://www.facebook.com/motiondecorator',
    instagram: 'https://instagram.com/motiondecorator',
    linkedin: 'https://www.linkedin.com/in/motiondecorator/',
    twitter: 'https://x.com/motiondecorator',
  }
};

// --- Services Data ---

export const SERVICES: Service[] = [
  {
    id: 'graphic-design',
    title: 'Graphic Design',
    description: 'Branding, posters, ads, and UI assets that define your visual identity.',
    icon: 'Palette',
    image: 'https://picsum.photos/id/106/1200/630',
    heroTitle: 'Visuals That Speak Louder Than Words',
    heroSubtitle: 'We craft compelling visual identities that resonate with your audience and elevate your brand presence across all mediums.',
    features: ['Brand Identity Design', 'Marketing Collateral', 'Social Media Creatives', 'Packaging Design', 'Corporate Branding'],
    deliverables: ['Logo & Brand Guidelines', 'Brochures & Flyers', 'Social Media Kits', 'Presentation Decks'],
    process: [
      { title: 'Discovery', desc: 'Understanding your brand values and audience.' },
      { title: 'Concept', desc: 'Sketching and brainstorming visual directions.' },
      { title: 'Design', desc: 'Crafting high-fidelity vectors and layouts.' },
      { title: 'Delivery', desc: 'Finalizing assets in all required formats.' },
    ],
    relatedPortfolioIds: ['2', '6'],
  },
  {
    id: 'web-dev',
    title: 'Web Design & Dev',
    description: 'Custom websites, high-converting landing pages, and seamless UI/UX.',
    icon: 'Globe',
    image: 'https://picsum.photos/id/1/1200/630',
    heroTitle: 'Websites That Convert & Captivate',
    heroSubtitle: 'From high-performance landing pages to complex corporate portals, we build digital experiences that drive growth.',
    features: ['Custom UI/UX Design', 'Responsive Web Development', 'E-commerce Solutions', 'Landing Page Optimization', 'CMS Integration'],
    deliverables: ['Figma Prototypes', 'Fully Responsive Website', 'SEO-Ready Code', 'Content Management System'],
    process: [
      { title: 'Wireframing', desc: 'Mapping out user journeys and structure.' },
      { title: 'UI Design', desc: 'Creating the visual look and feel.' },
      { title: 'Development', desc: 'Coding with modern frameworks (React, Tailwind).' },
      { title: 'Launch', desc: 'Testing, optimizing, and going live.' },
    ],
    relatedPortfolioIds: ['1', '5', '7'],
  },
  {
    id: 'social-media',
    title: 'Social Media Mgmt',
    description: 'Strategic content calendars, engagement growth, and creative posts.',
    icon: 'Smartphone',
    image: 'https://picsum.photos/id/129/1200/630',
    heroTitle: 'Building Communities, Not Just Followers',
    heroSubtitle: 'We manage your social presence end-to-end, creating content that engages, entertains, and converts.',
    features: ['Strategy Development', 'Content Creation (Static & Video)', 'Community Management', 'Influencer Collaboration', 'Analytics & Reporting'],
    deliverables: ['Monthly Content Calendar', '15-30 Creatives/Month', 'Engagement Reports', 'Growth Strategy'],
    process: [
      { title: 'Audit', desc: 'Analyzing current presence and competitors.' },
      { title: 'Strategy', desc: 'Defining pillars, tone, and schedule.' },
      { title: 'Creation', desc: 'Producing visuals and copy.' },
      { title: 'Management', desc: 'Posting, engaging, and reporting.' },
    ],
    relatedPortfolioIds: ['4', '8'],
  },
  {
    id: 'digital-marketing',
    title: 'Digital Marketing',
    description: 'SEO, Google Ads, Meta funnels, and data-driven growth strategies.',
    icon: 'TrendingUp',
    image: 'https://picsum.photos/id/352/1200/630',
    heroTitle: 'Data-Driven Strategies for Real ROI',
    heroSubtitle: 'Stop guessing. We use proven frameworks to attract quality leads and scale your revenue through paid and organic channels.',
    features: ['Search Engine Optimization (SEO)', 'PPC (Google Ads)', 'Social Media Advertising', 'Email Marketing Funnels', 'Conversion Rate Optimization'],
    deliverables: ['Campaign Setup & Management', 'SEO Audit & Implementation', 'Weekly Performance Reports', 'A/B Testing Results'],
    process: [
      { title: 'Research', desc: 'Keyword analysis and audience targeting.' },
      { title: 'Setup', desc: 'Configuring campaigns and tracking pixels.' },
      { title: 'Optimization', desc: 'Continuous tweaking for lower CPC/CPA.' },
      { title: 'Scale', desc: 'Increasing budget on winning strategies.' },
    ],
    relatedPortfolioIds: ['6', '9'],
  },
  {
    id: 'motion-graphics',
    title: 'Motion & Video',
    description: 'Logo animation, product reveals, and professional video editing.',
    icon: 'Film',
    image: 'https://picsum.photos/id/392/1200/630',
    heroTitle: 'Motion That Moves Your Audience',
    heroSubtitle: 'In a video-first world, we create dynamic motion graphics and cinematic edits that stop the scroll.',
    features: ['2D/3D Motion Graphics', 'Explainer Videos', 'Logo Animation', 'Product Promos', 'Reels & TikTok Editing'],
    deliverables: ['Storyboards', 'High-Res Video Files', 'Source Files (AE/Premiere)', 'Sound Design'],
    process: [
      { title: 'Scripting', desc: 'Crafting the narrative and flow.' },
      { title: 'Storyboarding', desc: 'Visualizing key frames.' },
      { title: 'Animation', desc: 'Bringing static assets to life.' },
      { title: 'Sound', desc: 'Adding SFX and voiceovers.' },
    ],
    relatedPortfolioIds: ['3', '10', '11'],
  },
  {
    id: 'branding',
    title: 'Branding',
    description: 'Complete brand identity systems, strategy, and storytelling.',
    icon: 'Award',
    image: 'https://picsum.photos/id/250/1200/630',
    heroTitle: 'Defining Who You Are',
    heroSubtitle: 'More than just a logo. We build comprehensive brand systems that tell your story and build trust.',
    features: ['Brand Strategy', 'Logo Design', 'Typography & Color Theory', 'Brand Voice Guidelines', 'Stationery Design'],
    deliverables: ['Brand Book', 'Logo Suite (SVG, PNG, EPS)', 'Typography System', 'Social Media Assets'],
    process: [
      { title: 'Workshop', desc: 'Defining brand archetype and values.' },
      { title: 'Exploration', desc: 'Developing multiple visual directions.' },
      { title: 'Refinement', desc: 'Polishing the chosen direction.' },
      { title: 'Guidelines', desc: 'Documenting usage rules.' },
    ],
    relatedPortfolioIds: ['2', '12'],
  },
  {
    id: 'it-services',
    title: 'IT Solutions',
    description: 'Website maintenance, server hosting, and technical support.',
    icon: 'Zap',
    image: 'https://picsum.photos/id/0/1200/630',
    heroTitle: 'Reliable Tech Foundations',
    heroSubtitle: 'We ensure your digital infrastructure is secure, fast, and always online.',
    features: ['Website Maintenance', 'Cloud Hosting Setup', 'CMS Automation', 'Security Audits', 'Technical Support'],
    deliverables: ['99.9% Uptime', 'Monthly Security Patches', 'Performance Optimization', 'Technical Consultation'],
    process: [
      { title: 'Audit', desc: 'Checking current infrastructure health.' },
      { title: 'Setup', desc: 'Migrating or configuring servers.' },
      { title: 'Monitor', desc: '24/7 uptime and security tracking.' },
      { title: 'Support', desc: 'On-demand troubleshooting.' },
    ],
    relatedPortfolioIds: ['13', '14'],
  },
];

// --- Portfolio Data ---

export const PORTFOLIO: PortfolioItem[] = [
  {
    id: '1',
    title: 'Neon Nexus Website',
    category: 'Web',
    imageUrl: 'https://picsum.photos/id/1/800/600',
    description: 'A futuristic landing page for a tech startup.',
    client: 'Neon Nexus AI',
    year: '2023',
    tags: ['React', 'Three.js', 'Tailwind CSS'],
    challenge: 'Neon Nexus needed a website that visually represented their complex AI algorithms without overwhelming users. They wanted a "Cyberpunk meets Corporate" aesthetic.',
    solution: 'We built a 3D-heavy immersive experience using Three.js for the hero section, backed by a clean React architecture for content. The result is a high-performance site that feels like a sci-fi interface.',
    results: [
      { label: 'Load Time', value: '< 2s' },
      { label: 'Conversion Rate', value: '+150%' },
    ],
    gallery: ['https://picsum.photos/id/2/800/600', 'https://picsum.photos/id/3/800/600'],
  },
  {
    id: '2',
    title: 'EcoBrand Identity',
    category: 'Branding',
    imageUrl: 'https://picsum.photos/id/20/800/600',
    description: 'Complete rebranding for a sustainable energy firm.',
    client: 'EcoEnergy Solutions',
    year: '2022',
    tags: ['Illustrator', 'Branding Strategy'],
    challenge: 'EcoEnergy had a dated look that didn\'t reflect their modern sustainable tech. They needed a fresh, trust-inducing identity.',
    solution: 'We chose a palette of deep greens and electric blues to signify nature + technology. The new logo is a minimalist leaf-circuit hybrid.',
    results: [
      { label: 'Brand Awareness', value: '+40%' },
    ],
  },
  {
    id: '3',
    title: 'Urban Shoes Promo',
    category: 'Motion',
    imageUrl: 'https://picsum.photos/id/160/800/600',
    description: 'High-energy product reveal animation.',
    client: 'Urban Shoes Co.',
    year: '2023',
    tags: ['After Effects', 'Cinema 4D'],
    challenge: 'Launch a new sneaker line with zero physical footage available before the prototype phase.',
    solution: 'We created a full CGI product reveal video. Dynamic camera angles and energetic typography built hype before the physical product existed.',
    results: [
      { label: 'Views', value: '1.2M' },
      { label: 'Pre-orders', value: '5,000+' },
    ],
  },
  {
    id: '4',
    title: 'Coffee House Social',
    category: 'Social',
    imageUrl: 'https://picsum.photos/id/425/800/600',
    description: 'Instagram campaign that increased engagement by 200%.',
    client: 'Daily Brews',
    year: '2024',
    tags: ['Content Strategy', 'Photography'],
    challenge: 'Daily Brews was losing market share to big chains. They needed to build a loyal local community.',
    solution: 'We shifted their content strategy to focus on "Morning Rituals" and user-generated content. We launched a hashtag campaign #MyDailyBrew.',
    results: [
      { label: 'Engagement', value: '+200%' },
      { label: 'Followers', value: '+5k' },
    ],
  },
  {
    id: '5',
    title: 'FinTech Dashboard',
    category: 'Web',
    imageUrl: 'https://picsum.photos/id/48/800/600',
    description: 'User-friendly dashboard for financial tracking.',
    client: 'WealthWise',
    year: '2023',
    tags: ['Figma', 'React', 'D3.js'],
    challenge: 'Users found the old dashboard confusing and cluttered.',
    solution: 'We redesigned the UX to prioritize key metrics. Dark mode was introduced for power users.',
    results: [
      { label: 'User Retention', value: '+25%' },
    ],
  },
  {
    id: '6',
    title: 'Summer Sale Ads',
    category: 'Ads',
    imageUrl: 'https://picsum.photos/id/180/800/600',
    description: 'High-converting ad creatives for Meta platforms.',
    client: 'FashionNova Inc.',
    year: '2023',
    tags: ['Performance Marketing', 'Motion Design'],
    challenge: 'Lower CPC and increase ROAS during the competitive summer season.',
    solution: 'We A/B tested 50+ creatives. The winning formula was fast-paced motion graphics combined with bold discount typography.',
    results: [
      { label: 'ROAS', value: '4.5x' },
    ],
  },
  {
    id: '7',
    title: 'Real Estate 360',
    category: 'Web',
    imageUrl: 'https://picsum.photos/id/10/800/600',
    description: 'Premium corporate website for luxury real estate.',
    client: 'Luxe Estates',
    year: '2024',
    tags: ['Next.js', 'Mapbox', 'UI/UX'],
    challenge: 'Showcase million-dollar properties with a web experience to match.',
    solution: 'We implemented virtual tours and a seamless map search interface using Mapbox.',
    results: [{ label: 'Leads', value: '+60%' }],
  },
  {
    id: '8',
    title: 'KidsMate SMM',
    category: 'Social',
    imageUrl: 'https://picsum.photos/id/104/800/600',
    description: 'Boosted engagement through product reels.',
    client: 'KidsMate Toys',
    year: '2023',
    tags: ['Reels', 'Strategy'],
    challenge: 'Reach parents of toddlers effectively on Instagram.',
    solution: 'Created educational yet fun reels showcasing the toys in action.',
    results: [{ label: 'Reach', value: '500k' }],
  },
  {
    id: '9',
    title: 'Local SEO Growth',
    category: 'Ads',
    imageUrl: 'https://picsum.photos/id/119/800/600',
    description: 'Local SEO traffic growth for a dental clinic.',
    client: 'BrightSmile',
    year: '2023',
    tags: ['SEO', 'Google My Business'],
    challenge: 'The clinic was invisible on Google Maps in their area.',
    solution: 'Complete GMB optimization and local citation building.',
    results: [{ label: 'Traffic', value: '+300%' }],
  },
  {
    id: '10',
    title: 'Unicorn Animation',
    category: 'Motion',
    imageUrl: 'https://picsum.photos/id/158/800/600',
    description: 'Fantasy animation reel demo.',
    client: 'DreamWorks Studio (Pitch)',
    year: '2022',
    tags: ['Character Animation', 'Maya'],
    challenge: 'Demonstrate high-end character animation capabilities.',
    solution: 'A 30-second fluid animation of a mythical creature.',
    results: [{ label: 'Award', value: 'Best Short' }],
  },
  {
    id: '11',
    title: 'Tech Logo Reveal',
    category: 'Motion',
    imageUrl: 'https://picsum.photos/id/18/800/600',
    description: 'Corporate logo motion reveal.',
    client: 'CyberSystems',
    year: '2023',
    tags: ['After Effects'],
    challenge: 'Make a boring text logo feel innovative.',
    solution: 'Used circuit board transitions to reveal the logo.',
    results: [{ label: 'Satisfaction', value: '100%' }],
  },
  {
    id: '12',
    title: 'Fashion Label Brand',
    category: 'Branding',
    imageUrl: 'https://picsum.photos/id/338/800/600',
    description: 'Brand guidelines for a new clothing line.',
    client: 'Velvet Thread',
    year: '2024',
    tags: ['Typography', 'Layout'],
    challenge: 'Establish a luxury feel for a mid-range price point brand.',
    solution: 'Elegant serif typography paired with monochromatic photography.',
    results: [{ label: 'Brand Value', value: 'High' }],
  },
  {
    id: '13',
    title: 'CMS Automation',
    category: 'IT',
    imageUrl: 'https://picsum.photos/id/445/800/600',
    description: 'Automating content workflows for a news site.',
    client: 'Daily News',
    year: '2023',
    tags: ['Python', 'AWS'],
    challenge: 'Editors were spending too much time manually formatting posts.',
    solution: 'Built a custom middleware to auto-format and publish.',
    results: [{ label: 'Time Saved', value: '20hrs/week' }],
  },
  {
    id: '14',
    title: 'Security Upgrade',
    category: 'IT',
    imageUrl: 'https://picsum.photos/id/531/800/600',
    description: 'Server security hardening for an e-commerce platform.',
    client: 'ShopSafe',
    year: '2023',
    tags: ['Cybersecurity', 'Linux'],
    challenge: 'Prevent recurring DDoS attacks.',
    solution: 'Implemented Cloudflare protection and server-level firewalls.',
    results: [{ label: 'Downtime', value: '0%' }],
  }
];

// --- Testimonials ---

export const TESTIMONIALS: Testimonial[] = [
  {
    id: 't1',
    name: 'Sarah Jenkins',
    role: 'Marketing Director',
    company: 'TechFlow',
    content: 'Motion Decorator completely transformed our digital presence. Their 360-degree approach meant we didn\'t have to juggle multiple agencies. Stunning work!',
    rating: 5,
    avatar: 'https://picsum.photos/id/64/100/100',
  },
  {
    id: 't2',
    name: 'David Chen',
    role: 'Founder',
    company: 'StartUp Inc.',
    content: 'The ROI on their digital marketing campaigns has been phenomenal. Coupled with their motion graphics, our brand stands out like never before.',
    rating: 5,
    avatar: 'https://picsum.photos/id/91/100/100',
  },
  {
    id: 't3',
    name: 'Elena Rodriguez',
    role: 'Product Manager',
    company: 'Luxe Goods',
    content: 'Fast delivery, premium quality, and a team that genuinely cares about your vision. Highly recommended for any creative needs.',
    rating: 4,
    avatar: 'https://picsum.photos/id/65/100/100',
  },
];

// --- Pricing ---

export const PRICING: PricingPlan[] = [
  {
    id: 'starter',
    name: 'Starter',
    price: '$999',
    features: [
      'Basic Branding Kit',
      '5 Page Website',
      'Social Media Setup',
      '2 Motion Graphics',
    ],
  },
  {
    id: 'professional',
    name: 'Professional',
    price: '$2,499',
    features: [
      'Complete Identity System',
      'E-commerce Website',
      '1 Month Social Management',
      'SEO Optimization',
      'Promo Video (30s)',
    ],
    isPopular: true,
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    price: 'Custom',
    features: [
      'Full Scale Digital Strategy',
      'Custom App Development',
      'Dedicated Marketing Team',
      'Unlimited Creative Assets',
      'Priority 24/7 Support',
    ],
  },
];

// --- About Page Data ---

export const TEAM: TeamMember[] = [
  { name: 'Alex Rivera', role: 'Creative Director', image: 'https://picsum.photos/id/1005/200/200' },
  { name: 'Jessica Lee', role: 'Head of Marketing', image: 'https://picsum.photos/id/1011/200/200' },
  { name: 'Marcus Johnson', role: 'Lead Developer', image: 'https://picsum.photos/id/1025/200/200' },
];

export const ABOUT_CONTENT = {
  mission: "To empower businesses by blending artistic creativity with cutting-edge technology, delivering 360-degree digital solutions that drive real growth.",
  story: "Founded in 2013, Motion Decorator started as a small graphic design studio. Over the last decade, we've evolved into a full-service digital agency, helping over 500+ clients transform their digital footprint.",
};
